name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slash_command_dispatch:
    uses: MapColonies/shared-workflows/.github/workflows/slash-command.yaml@v3.1.0
    secrets: inherit
