name: test

on:
  issue_comment:
    types: [created]
  
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'pg-check'
    
    steps:
      - name: Check object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      - name: Check out Git repository
        id: checkout
        uses: actions/checkout@v4
      #- name: PR Comment
      #  uses: actions/github-script@v7
      #  with:
      #    script: |
      #      github.rest.issues.createComment({
      #        issue_number: context.issue.number,
      #        owner: context.repo.owner,
      #        repo: context.repo.repo,
      #        body: '${{ steps.checkout.outcome == 'success' && ':white_check_mark:' || ':x:' }} run ${{ github.event.comment.body }}'
      #      })
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: This comment was written by a bot!
  
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            '${{ steps.checkout.outcome == 'success' && ':white_check_mark:' || ':x:' }} run ${{ github.event.comment.body }}'
          reactions: rocket
  
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            This comment has been updated!
          reactions: hooray
